title:              Redan Hassoun
email:              redan.has.1991@gmail.com
description:        Blog
author:             Redan Hassoun
baseurl:            "/RedanHassoun"
url:                "https://RedanHassoun.github.io"

# Social Profiles
twitter_username:   HassounRedan
github_username:    RedanHassoun
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:  redan-hassoun

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
